/*
 * VERSION: dal4.6.5.DreamForge+Nighthawk+OS/2
 * DATE:    Thu May 28 12:25:26 PDT 1998
 *
 * This file is automatically generated and will be updated each time you
 * run Config.  YOU SHOULD NOT EDIT THIS FILE.  Instead, edit "Options" in
 * the same directory as Config, and rerun to regenerate this file.
 */

#define DPATH "./"
#define SPATH "./ircd.exe"
#define LISTEN_SIZE 5
#define MAXSENDQLENGTH 2000000
#define BUFFERPOOL (4 * MAXSENDQLENGTH)
#define MAXCONNECTIONS 128
#define NICKNAMEHISTORYLENGTH 200
#define SHOWOPERS
#define HUB 1
#undef CRYPT_OPER_PASSWORD
#undef CRYPT_LINK_PASSWORD
#undef UNIXPORT
#undef NOSPOOF
#define NOSPOOF_SEED01 0x69130012
#define NOSPOOF_SEED02 0x00126913
#define CONTACT_EMAIL "nth.tech@iname.com"
#define SERVICES_NAME "none"
#define KLINE_ADDRESS "nth.tech@iname.com"
#define DOMAINNAME "nighthawk.smartt.com"
